AppynittyWebApp/Models/Career.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace AppynittyWebApp.Models
{
    public partial class Career
    {
        [Key]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Date { get; set; }
        [StringLength(500)]
        public string JobTitle { get; set; }
        [Column("Min_Exp")]
        public string MinExp { get; set; }
        [Column("Max_Exp")]
        public string MaxExp { get; set; }
        [Column("Min_Salary")]
        public string MinSalary { get; set; }
        [Column("Max_Salary")]
        public string MaxSalary { get; set; }
        [Column("Job_Location")]
        public string JobLocation { get; set; }
        [Column("Job_Desc")]
        public string JobDesc { get; set; }
        [Column("isActive")]
        public bool IsActive { get; set; }
    }
}

AppynittyWebApp/Controllers/CareersController.cs
using AppynittyWebApp.Models;
using AppynittyWebApp.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.Protocols;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace AppynittyWebApp.Controllers
{
    public class CareersController : Controller
    {
        private readonly AppynittyCommunicationContext _context;
        private readonly IWebHostEnvironment webHostEnvironment;

        public CareersController(AppynittyCommunicationContext context, IWebHostEnvironment hostEnvironment, IConfiguration configuration)
        {
            _context = context;
            webHostEnvironment = hostEnvironment;
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        //var connectionString = Configuration.GetConnectionString("AppynittyWebAppContextConnection");

        private SqlConnection con;
        private void connection()
        {
            string constring = Configuration.GetConnectionString("AppynittyWebAppContextConnection").ToString();
            con = new SqlConnection(constring);
        }
        public IActionResult Index()
        {
            var Email = User.FindFirstValue(ClaimTypes.Email);
            if(Email != null)
            {
                TempData["Email"] = Email;

                //CarrersDetailsVM CVDetail = new CarrersDetailsVM();
                //List<CarrersDetailsIteam> ListAppEmpCVItems = new List<CarrersDetailsIteam>();
                //string StoredProc = "exec CarrersDetails ";
                //var data = _context.CarrersDetails.FromSqlRaw(StoredProc).ToList();

                //if (data != null && data.Count > 0)
                //{
                //    CVDetail.ListCarrersDetails = data.Select(x => new CarrersDetailsIteam()
                //    {
                //        Id = x.Id,
                //        Date = x.Date,
                //        JobTitle = x.JobTitle,
                //        IsActive = x.IsActive,
                //        CareersCount = x.CareersCount
                //    })
                //   .ToList();
                //}

                return View();


                //var career = await _context.Careers.ToListAsync();
                //return View(career);
            }
            else
            {
                return Redirect("/Identity/Account/Login");
            }
        }


        [HttpPost]
        public IActionResult LoadCarrersData()
        {
            try
            {
                var draw = HttpContext.Request.Form["draw"].FirstOrDefault();

                // Skip number of Rows count  
                var start = Request.Form["start"].FirstOrDefault();

                // Paging Length 10,20  
                var length = Request.Form["length"].FirstOrDefault();

                // Sort Column Name  
                var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();

                // Sort Column Direction (asc, desc)  
                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();

                // Search Value from (Search box)  
                var searchValue = Request.Form["search[value]"].FirstOrDefault();

                //Paging Size (10, 20, 50,100)  
                int pageSize = length != null ? Convert.ToInt32(length) : 0;

                int skip = start != null ? Convert.ToInt32(start) : 0;

                int recordsTotal = 0;

                string StoredProc = "exec CarrersDetails ";
                // getting all Customer data  
                var customerData = (from tempcustomer in _context.CarrersDetails.FromSqlRaw(StoredProc).ToList()
                                    select tempcustomer);
                //Sorting  
                //if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDirection)))
                //{
                //    customerData = customerData.OrderBy(sortColumn + " " + sortColumnDirection);

                //}
                //Search  
                if (!string.IsNullOrEmpty(searchValue))
                {
                    customerData = customerData.Where(m => m.JobTitle.ToLower().Contains(searchValue.ToLower()));
                }

                //total number of rows counts   
                recordsTotal = customerData.Count();
                //Paging   
                var data = customerData.Skip(skip).Take(pageSize).ToList();
                //Returning Json Data  
                return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data });

            }
            catch (Exception)
            {
                throw;
            }

        }
        // GET: CareersController/Create
        public async Task<ActionResult> AddOrEdit(int? Id)
        {
           

            var Email = User.FindFirstValue(ClaimTypes.Email);
            if (Email != null)
            {
                TempData["Email"] = Email;
                ViewBag.PageName = Id == null ? "Create Job" : "Edit Job";
                ViewBag.IsEdit = Id == null ? false : true;
                if (Id == null)
                {
                    return View();
                }
                else
                {
                    var careers = await _context.Careers.FindAsync(Id);

                    if (careers == null)
                    {
                        return NotFound();
                    }
                    return View(careers);
                }
            }
            else
            {
                return Redirect("/Identity/Account/Login");
            }
        }
        // POST: CareersController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit(int Id,
            [Bind("Id,Date,JobTitle,MinExp,MaxExp,MinSalary,MaxSalary,JobLocation,JobDesc,IsActive")] Career CareerData)
        {
            bool IsnewsExist = false;

            Career career = await _context.Careers.FindAsync(Id);

            if (career != null)
            {
                IsnewsExist = true;
            }
            else
            {
                career = new Career();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    career.Date = CareerData.Date;
                    career.JobTitle = CareerData.JobTitle;
                    career.MinExp = CareerData.MinExp;
                    career.MaxExp = CareerData.MaxExp;
                    career.MinSalary = CareerData.MinSalary;
                    career.MaxSalary = CareerData.MaxSalary;
                    career.JobDesc = CareerData.JobDesc;
                    career.JobLocation = CareerData.JobLocation;
                    career.IsActive = CareerData.IsActive;

                    if (IsnewsExist)
                    {
                        _context.Update(career);
                    }
                    else
                    {
                        _context.Add(career);
                    }
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(CareerData);
        }


        // GET: CareersController/Details/5
        public async Task<IActionResult> Details(int? Id)
        {
          

            var Email = User.FindFirstValue(ClaimTypes.Email);
            if (Email != null)
            {
                TempData["Email"] = Email;
                if (Id == null)
                {
                    return NotFound();
                }
                var careers = await _context.Careers.FirstOrDefaultAsync(m => m.Id == Id);
                if (careers == null)
                {
                    return NotFound();
                }
                return View(careers);
            }
            else
            {
                return Redirect("/Identity/Account/Login");
            }
        }

        // GET: CareersController/Delete/5
        public async Task<IActionResult> Delete(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            var career = await _context.Careers.FirstOrDefaultAsync(m => m.Id == Id);

            return View(career);
        }

        // POST: CareersController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int Id)
        {
            var career = await _context.Careers.FindAsync(Id);
            _context.Careers.Remove(career);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> OpenPosition(CareersVM model)
        {

            var careersData = await _context.Careers.Where(o => o.IsActive == true).OrderByDescending(o => o.Id).ToListAsync();

            ViewBag.careerslist = careersData;

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> CVSection()
        {
            ViewData["JobList"] = new SelectList(_context.Careers, "Id", "JobTitle");

            var JobListData = await _context.Careers.Where(o => o.IsActive == true).OrderByDescending(o => o.Id).ToListAsync();
            ViewBag.Joblist = JobListData;
            return View();
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]

AppynittyWebApp/Views/Careers/AddOrEdit.cshtml
@model AppynittyWebApp.Models.Career

@{
    ViewData["Title"] = "Create";
    Layout = "_AdminLayout";
}



@*<style>
        input[type=checkbox] {
            box-sizing: border-box;
            padding: 0;
            font-size: 4px;
            margin-top: -5%;
            margin-left: -31%;
        }
    </style>*@
<div class="container p-3 my-3 border">
    @*<h1> @ViewBag.PageName</h1>*@

    <div class="row">
        <div class="col-sm-6">
            <hr />
            <form asp-action="AddOrEdit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                @if (@ViewBag.IsEdit)
                {
                    <input type="hidden" asp-for="Id" />
                }
                <div class="form-group">
                    <label asp-for="Date" class="control-label"></label>
                    <input asp-for="Date" class="form-control" />
                    <span asp-validation-for="Date" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="JobTitle" class="control-label"></label>
                    <input asp-for="JobTitle" class="form-control" />
                    <span asp-validation-for="JobTitle" class="text-danger"></span>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="MinExp" class="control-label">Minimum Experience</label>
                            <input type="number" asp-for="MinExp" class="form-control" min="0" />
                            <span asp-validation-for="MinExp" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="MaxExp" class="control-label">Maximun Experience</label>
                            <input type="number" asp-for="MaxExp" class="form-control" min="0" max="30" />
                            <span asp-validation-for="MaxExp" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="MinSalary" class="control-label">Minimum Salary</label>
                            <input asp-for="MinSalary" class="form-control" />
                            <span asp-validation-for="MinSalary" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="MaxSalary" class="control-label">Maximun Salary</label>
                            <input asp-for="MaxSalary" class="form-control" />
                            <span asp-validation-for="MaxSalary" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="JobLocation" class="control-label"></label>
                    <input asp-for="JobLocation" class="form-control" />
                    <span asp-validation-for="JobLocation" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="JobDesc" class="control-label"></label>
                    @*<input asp-for="NewsEng" class="form-control" />*@
                    <textarea id="JobDesc" name="JobDesc" asp-for="JobDesc" class="form-control" rows="10" cols="100"></textarea>
                    <span asp-validation-for="JobDesc" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="IsActive" class="control-label"></label>
                    @*@Html.CheckBox("isActive")*@
                    @*<input id="IsActive" type="checkbox" name="IsActive" value="IsActive" />*@
                    <input type="checkbox" asp-for="IsActive" />
                    @*<span asp-validation-for="IsActive" class="text-danger"></span>*@
                </div>
                <div class="form-group">
                    <input class="btn btn-primary" type="submit" value="Save" />
                    <a class="btn btn-danger" asp-action="Index">Back</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script src="https://cdn.ckeditor.com/4.19.1/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('JobDesc');
    </script>
}

AppynittyWebApp/Views/Careers/CVSection.cshtml
@*@model AppynittyWebApp.Models.Career*@
@model AppynittyWebApp.ViewModels.CareersVM
@*@model IEnumerable<AppynittyWebApp.Models.News>*@

@{
    ViewData["Title"] = "Open Position";
}
<style>
    .newttl {
        list-style-type: none;
    }
    body{background:#e6e6e6}
</style>


<div class="container">
    <h1 style="text-align:center;" class="py-4">Careers Section</h1>

    <form enctype="multipart/form-data" asp-action="CVSection">
        <hr />

        <div class="contact-form-section">

            <div class="container">
                @{
                    var obj = ViewBag.Joblist;
                }

                <div class="form-section" style="padding-left:20%;width:80%">
                    <div class="f-g-s">
                        <div class="form-group">
                            <label asp-for="JobTitle" class="control-lable"></label>
                            <select asp-for="Id" name="Careers_Id" asp-items="ViewBag.Id" class="custom-select" required>
                                <option value="">Choose Position</option>
                                @foreach (var item in obj)
                                {
                                    <option value="@item.Id">@item.JobTitle</option>
                                }
                            </select>
                            <span asp-validation-for="Id" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="f-g-s">
                        <div class="form-group">
                            <label>Name</label>
                            <input asp-for="Name" class="form-control" placeholder="Name" type="text" required/>
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="f-g-s">
                        <div class="form-group">
                            <label>Email</label>
                            <input asp-for="Email" class="form-control" name="Email" placeholder="Enter Email Id" type="email" required>
                        </div>
                    </div>
                    <div class="f-g-s">
                        <div class="form-group">
                            <label>Mobile Number</label>
                            <input asp-for="MobileNo" class="form-control" name="MobileNo" placeholder="Enter Mobile Number" type="tel" required>
                        </div>
                    </div>
                    <div class="f-g-s">
                        <div class="form-group">
                            <label>Location</label>
                            <input asp-for="CurrentLocation" class="form-control" name="CurrentLocation" placeholder="Enter Current Location" required>
                        </div>
                    </div>
                    <div class="f-g-s">
                        <div class="form-group">
                            <label>Total Experience</label>
                            <select asp-for="TotExp" class="custom-select" required>
                                <option value="">Select</option>
                                <option value="Fresher">Fresher</option>
                                <option value="0">0</option>
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                                <option value="7">7</option>
                                <option value="8">8</option>
                                <option value="9">9</option>
                                <option value="10">10</option>
                                <option value="10+">10+</option>
                            </select>
                        </div>
                    </div>
                    <div class="f-g-s">
                        <label>Attach Resume/CV</label>
                        <div class="form-group">
                            <input type="file" asp-for="FileName" class="" id="customFile" required>
                        </div>
                    </div>
                    <div class="f-g-s">
                        <div class="form-group">
                            <input type="checkbox" asp-for="Tac" required/>
                            <label for="agreechkbox">I agree to the </label>
                            <a target="_blank" asp-action="TermsAndConditions"> Terms and Conditions</a>
                        </div>
                    </div>
                    <div class="f-g-s mb-5">
                        <div class="c-f-b">
                            <input class="btn btn-primary" type="submit" value="Save" />
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </form>

</div>

AppynittyWebApp/Views/Careers/Delete.cshtml
@model AppynittyWebApp.Models.Career
@{
    ViewData["Title"] = "Delete";
    Layout = "_AdminLayout";
}
<h2>Deleting Employee</h2>

<h3>Would you like to continue?</h3>
<div class="container p-3 my-3 border">
    <hr />
    <dl class="row">
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.JobTitle)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.JobTitle)
        </dd>
        <dt class="col-sm-3">
            Minimum Experience
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.MinExp)
        </dd>
        <dt class="col-sm-3">
            Maximum Experience
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.MaxExp)
        </dd>
        <dt class="col-sm-3">
            Minimum Salary
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.MinSalary)
        </dd>
        <dt class="col-sm-3">
            Maximum Salary
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.MaxSalary)
        </dd>
        <dt class="col-sm-3">
            Job Location
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.JobLocation)
        </dd>
        <dt class="col-sm-3">
            Job Description
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.JobDesc)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.IsActive)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input class="btn btn-primary" type="submit" value="Yes" />
        <a class="btn btn-danger" asp-action="Index">No</a>
    </form>

</div>

AppynittyWebApp/Views/Careers/Details.cshtml
@model AppynittyWebApp.Models.Career
@{
    ViewData["Title"] = "Details";
    Layout = "_AdminLayout";
}
<style>
    .rupee {
        content: "\20B9";
    }
</style>
<div class="container p-3 my-3 border">
    <h1>Job Details</h1>
    <hr />
    <dl class="row">
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.JobTitle)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.JobTitle)
        </dd>
        <dt class="col-sm-3">
             Experience
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.MinExp)<span>Yrs</span> - @Html.DisplayFor(model => model.MaxExp)<span>Yrs</span>
        </dd>
        <dt class="col-sm-3">
             Salary
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.MinSalary)<span class="rupee">&#8377;</span> - @Html.DisplayFor(model => model.MaxSalary)<span class="rupee">&#8377;</span>
        </dd>
        <dt class="col-sm-3">
            Job Location
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.JobLocation)
        </dd>
        <dt class="col-sm-3">
            Job Description
        </dt>
        <dd class="col-sm-9">
            @*@Html.DisplayFor(model => model.JobDesc)*@
            @Html.Raw(Model.JobDesc)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.IsActive)
        </dd>
    </dl>
    <div>
        <a class="btn btn-primary" asp-action="AddOrEdit" asp-route-Id="@Model.Id">Edit</a>
        <a class="btn btn-danger" asp-action="Index">Back</a>
    </div>
</div>

AppynittyWebApp/Views/Careers/Index.cshtml
@{
    Layout = "_AdminLayout";
    ViewData["Title"] = "Careers Section";
}
 
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<link href="//cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.dataTables.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.4.0/css/responsive.jqueryui.min.css" rel="stylesheet" />
<style>
    .danger {
        color: red !important;
    }

    .success {
        color: green !important;
    }
</style>
<h1 style="text-align: center; font-size: 1.8rem;">Job List</h1>
<div style="display: inline-flex;">
    <p style="text-align: left; margin-right: 20px;">
        <a class="btn btn-outline-danger" asp-area="Identity" asp-controller="Careers" asp-action="Index">Back</a>
    </p>
    <p style="text-align:right;margin-right:20px;">
        <a class="btn btn-outline-primary" asp-action="AddOrEdit">Create New</a>
    </p>
</div>
<div class="container">
    <br />
    <div style="width:90%; margin:0 auto;">
        <table id="example" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th></th>
                    <th>Date</th>
                    <th>Job Title</th>
                    <th>Status</th>
                    <th>Edit</th>
                    <th>Details</th>
                    <th>View Reply</th>
                </tr>
            </thead>
        </table>
    </div>
</div>

@section Scripts{
    <script src="//cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>

    <script>
        $(document).ready(function () {
            debugger;
            $('#example').DataTable({
                ajax: {
                    url: "Careers/LoadCarrersData",
                    type: "POST",
                },
                'responsive': {
                    'details': {
                        'type': 'column',
                        'target': 0
                    }
                },
                'columnDefs': [
                    {
                        'data': null,
                        'defaultContent': '',
                        'className': 'control',
                        'orderable': false,
                        'targets': 0
                    }
                ],
                processing: true,
                serverSide: true,
                filter: true,
                columns: [

                    { 'data': null },
                    {
                        "data": "date",
                        "render": function (data) {

                            var date = new Date(data);
                            var month = date.getMonth() + 1;
                            var hours = date.getHours();
                            var minutes = date.getMinutes();
                            var ampm = hours >= 12 ? 'pm' : 'am';
                            hours = hours % 12;
                            hours = hours ? hours : 12; // the hour '0' should be '12'
                            minutes = minutes < 10 ? '0' + minutes : minutes;

                            return date.getDate() + "/" + (month.toString().length > 1 ? month : "0" + month) + "/" + date.getFullYear() + "  " + hours + ':' + minutes + ' ' + ampm;
                        }
                    },
                    { data: "jobTitle", name: "JobTitle" },
                    /* { data: "isActive", name: "IsActive" },*/
                    {
                        render: function (data, type, full, meta) {
                            console.log(full);
                            if (full["isActive"] == true) {
                                return '<span class="success">Active</span>';
                            }
                            else {

                                return '<span class="danger">InActive</span>';
                            }
                        }
                    },
                    {
                        render: function (data, type, full, meta) { return '<a class="btn btn-outline-primary" onclick="AddOrEdit(' + full["id"] + ')" >Edit</a>'; }, "width": "10%"
                    },
                    {
                        render: function (data, type, full, meta) { return '<a class="btn btn-outline-primary" onclick="Details(' + full["id"] + ')" >Details</a>'; }, "width": "10%"
                    },
                    //{
                    //    render: function (data, type, full, meta)
                    //    {
                    //        return '<a class="btn btn-outline-primary mr-4" onclick="ViewCV(' + full["id"] + ')" >View</a> <span style = "padding: 3px 8px; background: green;color: white;border-radius:50%;" > ' + full["careersCount"] + '</span > '; }, "width": "10%"
                    //},
                    {
                        render: function (data, type, full, meta) {
                            if (full["careersCount"] > 0) {
                                return '<a class="btn btn-outline-primary" style="margin-right:0px;" onclick="ViewCV(' + full["id"] + ')" >View</a> <span style = "padding: 3px 8px; background: green;color: white;border-radius:50%;margin-right: 0px;" > ' + full["careersCount"] + '</span > ';

                            } else {
                                return '<a class="btn btn-outline-primary mr-4" onclick="ViewCV(' + full["id"] + ')" >View</a>';
                            }
                        }, "width": "10%"
                    },
                ]
            })

        });


        function AddOrEdit(id) {
            window.location.href = "/Careers/AddOrEdit?Id=" + id;
        };
        function Details(id) {
            window.location.href = "/Careers/Details?Id=" + id;
        };
        function ViewCV(id) {
            window.location.href = "/Careers/ViewCV?Id=" + id;
        };
    </script>
}